#!/bin/bash

build() {
    # CCID
    add_file /etc/libccid_Info.plist
    add_file /etc/reader.conf.d/libccidtwin
    add_file /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
    add_binary /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
    add_binary /usr/lib/pcsc/drivers/serial/libccidtwin.so

    # OPENSC
    add_file /etc/opensc.conf
    add_binary /usr/lib/opensc-pkcs11.so
    add_binary /usr/lib/pkcs11/opensc-pkcs11.so

    # PCSCLITE
    add_binary /usr/lib/libpcsclite.so
    add_binary /usr/lib/libpcsclite_real.so

    # PCSCD at boot before cryptsetup
    add_systemd_drop_in pcscd.service override <<'EOF'
[Unit]
DefaultDependencies=no

[Service]
ExecStart=
ExecStart=/usr/bin/pcscd --foreground --disable-polkit --auto-exit $PCSCD_ARGS
EOF
    add_systemd_drop_in pcscd.socket override <<'EOF'
[Unit]
DefaultDependencies=no
Before=cryptsetup.target

[Install]
RequiredBy=cryptsetup.target
EOF
    add_systemd_unit pcscd.service
    add_symlink /usr/lib/systemd/system/cryptsetup.target.requires/pcscd.socket ../pcscd.socket

    # MISC
    add_binary /usr/bin/p11tool
    add_file /etc/pkcs11/modules/opensc.module
}

help() {
    cat <<HELPEOF
Add and early start (ie before cryptsetup) the pcscd socket service. This
allow cryptsetup "pkcs11-uri=auto" to find yubikey piv based token. Required
package are: ccid opensc and pcsclite. Use with systemd and sd-encrypt hook.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
