#!/bin/sh
XDG_DATA_HOME="${XDG_DATA_HOME-"$HOME/.local/share"}"
INSTALL_DIR="$XDG_DATA_HOME/albion-online"

if ! cmp -s "$INSTALL_DIR/launcher/version.txt" /usr/share/albion-online/launcher/version.txt; then
    mkdir -p "$INSTALL_DIR"
    chmod 700 "$INSTALL_DIR"
    rm -rf "$INSTALL_DIR/launcher"
    cp -a /usr/share/albion-online/launcher "$INSTALL_DIR"
fi

# FIXME: remove when qt scaling bug is fixed
export QT_AUTO_SCREEN_SCALE_FACTOR=0

export LD_PRELOAD="$INSTALL_DIR/game_x64/Albion-Online_Data/Plugins/x86_64/libSDL2-2.0.so.0"
"$INSTALL_DIR/launcher/Albion-Online"
